const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');const {spawn}=require('node:child_process');const server=spawn('python3',['-m','http.server','4175','--directory','.'],{stdio:'ignore'});
(async()=>{await new Promise(r=>setTimeout(r,1000));const b=await chromium.launch({headless:true});const page=await b.newPage({viewport:{width:1440,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));fs.mkdirSync('outputs/portfolio-previews',{recursive:true});
for(const slug of ['stereo-vision','wearable-ecg','deltav-control','waste-sorting']){
 await page.goto('http://127.0.0.1:4175/projects/'+slug+'/',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.detail-summary li').count(),slug==='stereo-vision'?4:3);assert.equal(await page.locator('.detail-process li').count(),4);assert.equal(await page.locator('.detail-technical article').count(),2);assert.ok(await page.locator('.detail-gallery figure').count()>=5);
 await page.evaluate(async()=>{for(const im of document.images)im.loading='eager';await Promise.all([...document.images].map(im=>im.decode()));});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'outputs/portfolio-previews/'+slug+'-desktop.png',fullPage:true});
 await page.locator('[data-lang="zh"]').click();assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN');assert.match(await page.locator('h2').first().textContent(),/项目简介/);await page.locator('[data-lang="en"]').click();assert.equal(await page.locator('html').getAttribute('lang'),'en');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'outputs/portfolio-previews/'+slug+'-mobile.png',fullPage:true});await page.locator('[data-lang="zh"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:1440,height:1000});console.log(slug+' passed');}
await page.goto('http://127.0.0.1:4175/',{waitUntil:'networkidle'});await page.locator('#about').scrollIntoViewIfNeeded();assert.match(await page.locator('.about-intro h2').textContent(),/Olivia/);assert.equal(await page.locator('.about-focus span').count(),5);await page.screenshot({path:'outputs/portfolio-previews/about-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('#about').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'outputs/portfolio-previews/about-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.locator('#projects').scrollIntoViewIfNeeded();assert.equal(await page.locator('.project-card').count(),4);assert.match(await page.locator('.project-card').nth(1).textContent(),/PCB integration/);assert.match(await page.locator('.project-card').nth(3).textContent(),/teammate/);await page.screenshot({path:'outputs/portfolio-previews/home-projects.png'});await page.locator('.language-switch button').nth(1).click();assert.match(await page.locator('.project-card').nth(3).textContent(),/队友/);assert.match(await page.locator('.about-story').textContent(),/机器人控制/);await page.locator('.project-card').nth(2).click();await page.waitForURL('**/projects/deltav-control/');assert.equal(await page.locator('.detail-process li').count(),4);assert.deepEqual(errors,[]);await b.close();server.kill();console.log('Homepage cards, bilingual content, native project navigation and desktop/mobile checks passed.');})().catch(e=>{console.error(e);server.kill();process.exit(1)});
